### ISSUE TITLE
submit hashes doesn't get the proof on ethereum

### ISSUE THREAD

**Issue by tyranthym** [chainpoint/chainpoint-client-js#3] opened 2018-07-31 01:48 UTC
I just followed readme sample code to test the functionalities, what I've done is that I used a sha256 library to hash some json data to strings, then submit to calendar via this library, now after 10 hr, when I call getproof(), it only show me cal and btc completed. not eth. we are working on an ethereum project, we need to write some data proofs on ethereum platform so the end user can verify these data later. My question is: 
1. Is the submithashes() work with ethereum platform? why I can't get the proofs 
2. if 1 is possible, is there any way I can configure that only write to ethereum platform?(not bitcoin)
3. I'm pretty sure I'm missing something here. what we need is writing some json format data to blockchain and can be verified easily. Do we need to write data to ethereum on our own then provide a proof(receipt I guess) or we hash the json data then submit via this service to ethereum? if this service nees to write something to blockchain, who will pay the gas?

**Comment by grempe** [comment] 2018-07-31 02:13
At this moment we do not anchor hashes to the Ethereum blockchain, we anchor to our Chainpoint Calendar and to the Bitcoin blockchain.

Based on what you described, if you are writing data to Ethereum and then you want to submit a hash of that data to the Chainpoint Network that is a possible path for you to take.

The Chainpoint Network pays all Bitcoin anchoring fees.

I'm closing this as its not a bug, but a question. Please feel free to use our support system in the future for similar questions:

https://tierion.com/contact/

Cheers

**Closed as completed by grempe** 2018-07-31 02:13 UTC

**Comment by tyranthym** [comment] 2018-07-31 02:32
Thanks for quick response. One last question, where is the transaction address on bitcoin blockchain for the proof? I can only see an anchor id on verifying response. anything returned i can use to search on https://www.blockchain.com/explorer?

**Comment by grempe** [comment] 2018-07-31 02:35
Using the `chainpoint-parse` lib will allow you to parse a proof and see that info. Please keep in mind though, we don't just anchor to a TX, we anchor all the way up to the Merkle Root of the Bitcoin Block that the TX is a part of.

https://github.com/chainpoint/chainpoint-parse

**Comment by tyranthym** [comment] 2018-07-31 02:38
I'll look into it, thanks so much!

**Comment by grempe** [comment] 2018-07-31 02:41
You can also take a look at this RunKit example which demonstrates verifying a proof directly with Bitcoin (without asking a Chainpoint Node to verify):

https://runkit.com/tierion/verify-a-chainpoint-proof-directly-using-bitcoin
